import { MAX_POSITION_LENGTH } from "@dielys/protocol";
import { describe, expect, it } from "vitest";
import {
  between,
  betweenMany,
  FIRST_POSITION,
  isValid,
  PositionError,
  validate,
} from "../src/domain/position.js";

/**
 * Fractional indexing (F5.5). These are the properties the Android client will
 * depend on, so most of them are stated as invariants over many operations
 * rather than as single examples — an ordering bug that only shows up at the
 * 62nd append is exactly the kind that reaches a phone.
 */

// Imported rather than read from disk: these tests run in workerd, which has
// no filesystem. The Kotlin suite reads the same file from resources.
import fixtures from "../../protocol/fixtures/positions.json";

describe("golden vectors (F4)", () => {
  // Hand-computed from the scheme, not generated by the code under test. The
  // Kotlin implementation must reproduce the same values from the same file.
  for (const vector of fixtures.between) {
    it(`between(${JSON.stringify(vector.before)}, ${JSON.stringify(vector.after)}) = ${vector.expected} — ${vector.why}`, () => {
      expect(between(vector.before, vector.after)).toBe(vector.expected);
    });
  }

  it("the ordering fixture is sorted by plain byte comparison", () => {
    const keys = fixtures.ordering.keys;
    expect([...keys].sort()).toEqual(keys);
  });

  it("every key in the ordering fixture is valid", () => {
    for (const key of fixtures.ordering.keys) expect(isValid(key)).toBe(true);
  });

  it("every key in the invalid fixture is rejected", () => {
    for (const key of fixtures.invalid.keys) expect(isValid(key)).toBe(false);
  });
});

describe("between", () => {
  it("starts an empty list at the documented first position", () => {
    expect(between(null, null)).toBe(FIRST_POSITION);
  });

  it("always returns something strictly between its neighbours", () => {
    const pairs: Array<[string, string]> = [
      ["a0", "a1"],
      ["a0", "az"],
      ["Zz", "a0"],
      ["a0V", "a0l"],
      ["b00", "b0z"],
      ["A00000000000000000000000001", "zzzzzzzzzzzzzzzzzzzzzzzzzzz"],
    ];
    for (const [before, after] of pairs) {
      const middle = between(before, after);
      expect(middle > before).toBe(true);
      expect(middle < after).toBe(true);
      expect(isValid(middle)).toBe(true);
    }
  });

  it("refuses neighbours that are out of order", () => {
    expect(() => between("a1", "a0")).toThrow(PositionError);
  });

  it("refuses neighbours that are equal — there is no room between them", () => {
    expect(() => between("a0", "a0")).toThrow(PositionError);
  });

  it("refuses an invalid neighbour rather than producing a key from it", () => {
    expect(() => between("not a position", null)).toThrow(PositionError);
    expect(() => between(null, "a00")).toThrow(PositionError);
  });
});

describe("appending", () => {
  it("keeps keys short and ordered across the length boundary", () => {
    let cursor: string | null = null;
    const keys: string[] = [];
    for (let i = 0; i < 200; i += 1) {
      cursor = between(cursor, null);
      keys.push(cursor);
    }

    expect([...keys].sort()).toEqual(keys);
    expect(new Set(keys).size).toBe(keys.length);
    // 62 two-character keys, then three characters — this is the property the
    // integer part exists for. A plain midpoint scheme would grow without bound.
    expect(keys[61]).toBe("az");
    expect(keys[62]).toBe("b00");
    expect(Math.max(...keys.map((k) => k.length))).toBe(3);
  });

  it("stays valid for a long run", () => {
    let cursor: string | null = null;
    for (let i = 0; i < 500; i += 1) {
      cursor = between(cursor, null);
      expect(isValid(cursor)).toBe(true);
    }
  });
});

describe("prepending", () => {
  it("walks down into the negative half without growing", () => {
    let cursor = FIRST_POSITION;
    const keys: string[] = [];
    for (let i = 0; i < 60; i += 1) {
      cursor = between(null, cursor);
      keys.push(cursor);
    }

    // Built in descending order, so reversing gives ascending.
    expect([...keys].reverse()).toEqual([...keys].sort());
    expect(keys[0]).toBe("Zz");
    expect(Math.max(...keys.map((k) => k.length))).toBe(2);
  });
});

describe("inserting between the same pair repeatedly", () => {
  it("grows one key at a time, which is why betweenMany exists", () => {
    let low = "a0";
    const lengths: number[] = [];
    for (let i = 0; i < 50; i += 1) {
      const middle = between(low, "a1");
      expect(middle > low).toBe(true);
      expect(middle < "a1").toBe(true);
      lengths.push(middle.length);
      low = middle;
    }
    // Documented degradation, not a bug: each insert lands in the gap the last
    // one left. The fix is to ask for all the keys at once.
    expect(lengths[0]).toBeLessThan(lengths[49] as number);
  });

  it("refuses to produce a key past the protocol bound", () => {
    // Drive it deliberately into the wall rather than letting the server
    // reject the mutation later with no explanation (F3).
    let low = "a0";
    let threw = false;
    for (let i = 0; i < 20000; i += 1) {
      try {
        low = between(low, "a1");
      } catch (error) {
        expect(error).toBeInstanceOf(PositionError);
        threw = true;
        break;
      }
      expect(low.length).toBeLessThanOrEqual(MAX_POSITION_LENGTH);
    }
    expect(threw).toBe(true);
  });
});

describe("betweenMany", () => {
  it("returns nothing for a count of zero", () => {
    expect(betweenMany("a0", "a1", 0)).toEqual([]);
  });

  it("matches between for a count of one", () => {
    expect(betweenMany("a0", "a1", 1)).toEqual([between("a0", "a1")]);
  });

  it("spreads keys instead of nesting them", () => {
    const keys = betweenMany("a0", "a1", 50);
    expect(keys).toHaveLength(50);
    expect([...keys].sort()).toEqual(keys);
    expect(new Set(keys).size).toBe(50);
    expect(keys.every((k) => k > "a0" && k < "a1")).toBe(true);
    // Bisecting keeps this at 3; inserting one at a time reaches 12.
    expect(Math.max(...keys.map((k) => k.length))).toBeLessThanOrEqual(4);
  });

  it("appends and prepends in bulk", () => {
    const appended = betweenMany("a0", null, 100);
    expect([...appended].sort()).toEqual(appended);
    expect(appended.every((k) => k > "a0")).toBe(true);

    const prepended = betweenMany(null, "a0", 100);
    expect([...prepended].sort()).toEqual(prepended);
    expect(prepended.every((k) => k < "a0")).toBe(true);
  });

  it("refuses a negative or fractional count", () => {
    expect(() => betweenMany("a0", "a1", -1)).toThrow(PositionError);
    expect(() => betweenMany("a0", "a1", 1.5)).toThrow(PositionError);
  });
});

describe("validate", () => {
  it("accepts well-formed keys", () => {
    for (const key of ["a0", "a1", "az", "b00", "Zz", "a0V", "A00000000000000000000000001"]) {
      expect(() => validate(key)).not.toThrow();
    }
  });

  it("rejects a trailing zero, which is a second spelling of the same key", () => {
    expect(() => validate("a0V0")).toThrow(PositionError);
  });

  it("rejects a key shorter than its own declared integer length", () => {
    // 'z' declares 27 characters.
    expect(() => validate("z0")).toThrow(PositionError);
  });

  it("rejects digits outside the alphabet", () => {
    expect(() => validate("a0!")).toThrow(PositionError);
    expect(() => validate("a0 ")).toThrow(PositionError);
  });

  it("rejects an empty key", () => {
    expect(() => validate("")).toThrow(PositionError);
  });
});

describe("simulated reordering (F5.5, H3.9)", () => {
  it("moving one item never changes any other key", () => {
    // Build a list, then move the last item to the middle. This is the whole
    // point of fractional indexing: exactly one row is written.
    const keys: string[] = [];
    let cursor: string | null = null;
    for (let i = 0; i < 10; i += 1) {
      cursor = between(cursor, null);
      keys.push(cursor);
    }

    const before = [...keys];
    const moved = between(keys[4] as string, keys[5] as string);
    const rest = before.slice(0, 9);

    expect(rest).toEqual(before.slice(0, 9));
    expect(moved > (keys[4] as string)).toBe(true);
    expect(moved < (keys[5] as string)).toBe(true);
  });

  it("two devices inserting at the same spot both survive, ordered by id", () => {
    // Neither device can see the other, so both may pick the same key. That is
    // expected — the list order is (position, id), and the UUIDv7 breaks the
    // tie identically on both devices.
    const deviceA = between("a0", "a1");
    const deviceB = between("a0", "a1");
    expect(deviceA).toBe(deviceB);

    const rows = [
      { position: deviceB, id: "018f2f6c-0000-7000-8000-00000000000b" },
      { position: deviceA, id: "018f2f6c-0000-7000-8000-00000000000a" },
    ];
    const sorted = [...rows].sort(
      (x, y) =>
        (x.position < y.position ? -1 : x.position > y.position ? 1 : 0) || (x.id < y.id ? -1 : 1),
    );
    expect(sorted.map((r) => r.id)).toEqual([
      "018f2f6c-0000-7000-8000-00000000000a",
      "018f2f6c-0000-7000-8000-00000000000b",
    ]);
    // Both rows are still there. Neither clobbered the other.
    expect(sorted).toHaveLength(2);
  });
});
